import json

SEED_PROJECTS = [
    {
        "id": "PRJ-001",
        "name": "National Highway Development Project (NH-48 Expansion)",
        "ministry": "Ministry of Road Transport and Highways",
        "sector": "Transport",
        "state": "Maharashtra",
        "agency": "National Highways Authority of India",
        "original_cost": 24500,
        "current_cost": 28930,
        "expenditure": 22100,
        "physical_progress": 67,
        "planned_progress": 78,
        "start_date": "2021-04-15",
        "expected_completion": "2025-12-31",
        "predicted_completion": "2027-03-15",
        "cost_overrun_probability": 72,
        "delay_probability": 79,
        "implementation_risk": 65,
        "risk_score": 74,
        "risk_level": "HIGH",
        "milestones_total": 24,
        "milestones_delayed": 9,
        "lat": 18.52,
        "lng": 73.85,
        "risk_factors": [
            "Physical progress is 11% behind planned progress",
            "Cost has increased by 18.1% from original estimate",
            "9 of 24 milestones are delayed",
            "Land acquisition pending in 3 critical stretches",
            "Monsoon season causing recurring construction pauses",
        ],
        "risk_inputs": {
            "weather": {"condition": "UNFAVOURABLE", "disruption": "HIGH", "workingDaysLost": 25},
            "ground": {"condition": "MODERATE"},
            "calamity": {"floodExposure": "MODERATE", "landslideExposure": "MODERATE"},
            "material": {"availability": "TIGHT", "priceIncreasePct": 8},
            "workforce": {"availability": "ADEQUATE", "productivity": "NORMAL"},
            "contractor": {"performance": "FAIR", "delayedMilestoneCount": 6},
            "engineering": {"reworkLevel": "LOW", "designChangeCount": 3},
            "clearance": {"landAcquiredPct": 80, "environmentalClearance": "CLEARED"},
            "administrative": {"turnaround": "NORMAL", "pendingApprovalCount": 4, "interDepartmentDependency": "HIGH"},
            "supplyChain": {"supplierDependency": "MODERATE"},
            "legalSocial": {"oppositionLevel": "LOW"},
        },
        "recommendations": [
            "Review delayed project milestones and prepare recovery plan",
            "Escalate land acquisition issues to state revenue department",
            "Increase monitoring frequency to bi-weekly status reviews",
            "Deploy additional resources for critical path activities",
            "Engage with district collectors for faster approvals",
        ],
    },
    {
        "id": "PRJ-002",
        "name": "Eastern Dedicated Freight Corridor",
        "ministry": "Ministry of Railways",
        "sector": "Transport",
        "state": "West Bengal",
        "agency": "Dedicated Freight Corridor Corporation of India",
        "original_cost": 48500,
        "current_cost": 53200,
        "expenditure": 41800,
        "physical_progress": 72,
        "planned_progress": 85,
        "start_date": "2019-07-01",
        "expected_completion": "2026-06-30",
        "predicted_completion": "2027-10-30",
        "cost_overrun_probability": 68,
        "delay_probability": 82,
        "implementation_risk": 61,
        "risk_score": 71,
        "risk_level": "HIGH",
        "milestones_total": 32,
        "milestones_delayed": 11,
        "lat": 22.82,
        "lng": 88.18,
        "risk_factors": [
            "Physical progress is 13% behind planned progress",
            "Cost overrun of 9.7% from original estimate",
            "11 of 32 milestones are overdue",
            "Bridge construction across multiple river crossings delayed",
            "Utility relocation conflicts in several sections",
        ],
        "risk_inputs": {
            "weather": {"condition": "MILD", "disruption": "MODERATE"},
            "ground": {"condition": "MODERATE", "groundwater": "MODERATE"},
            "calamity": {"floodExposure": "MODERATE"},
            "material": {"availability": "TIGHT", "priceIncreasePct": 6},
            "workforce": {"availability": "ADEQUATE", "productivity": "NORMAL"},
            "contractor": {"performance": "FAIR", "delayedMilestoneCount": 8},
            "engineering": {"reworkLevel": "MODERATE", "technicalComplexity": "HIGH", "designChangeCount": 5},
            "clearance": {"landAcquiredPct": 95, "environmentalClearance": "CLEARED"},
            "administrative": {"turnaround": "NORMAL", "interDepartmentDependency": "HIGH"},
            "supplyChain": {"supplierDependency": "MODERATE", "importDependency": True},
            "legalSocial": {"oppositionLevel": "LOW", "activeDisputeCount": 2},
        },
        "recommendations": [
            "Conduct contractor performance assessment for delayed sections",
            "Reassess project timeline with revised critical path analysis",
            "Coordinate with state utilities for expedited relocation",
            "Deploy additional engineering teams for bridge construction",
            "Establish weekly progress review meetings with all stakeholders",
        ],
    },
    {
        "id": "PRJ-003",
        "name": "River Basin Development Project",
        "ministry": "Ministry of Jal Shakti",
        "sector": "Water",
        "state": "Bihar",
        "agency": "Central Water Commission",
        "original_cost": 4800,
        "current_cost": 5822,
        "expenditure": 3200,
        "physical_progress": 48,
        "planned_progress": 62,
        "start_date": "2020-01-15",
        "expected_completion": "2025-08-31",
        "predicted_completion": "2027-12-31",
        "cost_overrun_probability": 76,
        "delay_probability": 88,
        "implementation_risk": 68,
        "risk_score": 91,
        "risk_level": "CRITICAL",
        "milestones_total": 18,
        "milestones_delayed": 12,
        "lat": 25.43,
        "lng": 85.62,
        "risk_factors": [
            "Physical progress is 14% behind planned progress",
            "Cost has increased by 21.3% from original estimate",
            "12 of 18 milestones are delayed including 5 critical ones",
            "Flood season has damaged completed infrastructure",
            "Expenditure utilization at 66.7% indicates spending delays",
        ],
        "risk_inputs": {
            "weather": {"condition": "SEVERE", "disruption": "CRITICAL", "workingDaysLost": 35},
            "ground": {"condition": "DIFFICULT", "groundwater": "HIGH"},
            "calamity": {"floodExposure": "HIGH", "landslideExposure": "MODERATE"},
            "material": {"availability": "SHORTAGE", "priceIncreasePct": 12, "criticalMaterial": True},
            "workforce": {"availability": "SHORTAGE", "productivity": "LOW"},
            "contractor": {"performance": "POOR", "delayedMilestoneCount": 9, "financialStress": "HIGH", "unresolvedIssueCount": 5},
            "engineering": {"reworkLevel": "MODERATE", "designChangeCount": 6},
            "clearance": {"landAcquiredPct": 65, "environmentalClearance": "PENDING", "rehabilitationPending": True},
            "administrative": {"turnaround": "SLOW", "pendingApprovalCount": 12, "interDepartmentDependency": "HIGH", "procurementDelay": True},
            "supplyChain": {"accessibility": "POOR", "supplierDependency": "HIGH"},
            "legalSocial": {"oppositionLevel": "MODERATE", "activeDisputeCount": 3, "unresolvedCompensation": 5},
        },
        "recommendations": [
            "Conduct urgent review of all delayed milestones",
            "Prepare flood damage assessment and restoration plan",
            "Engage with state irrigation department for coordination",
            "Request additional budget allocation for flood mitigation",
            "Deploy rapid assessment team for on-site evaluation",
        ],
    },
    {
        "id": "PRJ-004",
        "name": "Ultra Mega Solar Park Expansion",
        "ministry": "Ministry of New and Renewable Energy",
        "sector": "Energy",
        "state": "Rajasthan",
        "agency": "Solar Energy Corporation of India",
        "original_cost": 12800,
        "current_cost": 14520,
        "expenditure": 11200,
        "physical_progress": 73,
        "planned_progress": 82,
        "start_date": "2021-06-01",
        "expected_completion": "2025-10-31",
        "predicted_completion": "2026-08-15",
        "cost_overrun_probability": 58,
        "delay_probability": 69,
        "implementation_risk": 55,
        "risk_score": 63,
        "risk_level": "HIGH",
        "milestones_total": 20,
        "milestones_delayed": 7,
        "lat": 27.53,
        "lng": 71.92,
        "risk_factors": [
            "Physical progress is 9% behind planned progress",
            "Cost overrun of 13.4% due to panel price escalation",
            "Transmission line connectivity delays with state grid",
            "Sandstorm disruptions during summer months",
            "Contractor facing module supply chain issues",
        ],
        "risk_inputs": {
            "weather": {"condition": "CLEAR", "workingDaysLost": 5},
            "ground": {"condition": "FAVOURABLE"},
            "calamity": {"cycloneExposure": "LOW", "droughtExposure": "MODERATE"},
            "material": {"availability": "SHORTAGE", "priceIncreasePct": 15, "criticalMaterial": True},
            "workforce": {"availability": "ADEQUATE", "productivity": "HIGH"},
            "contractor": {"performance": "FAIR", "delayedMilestoneCount": 3},
            "engineering": {"reworkLevel": "LOW", "designChangeCount": 2},
            "clearance": {"landAcquiredPct": 100, "environmentalClearance": "PENDING"},
            "administrative": {"turnaround": "NORMAL", "pendingApprovalCount": 5, "interDepartmentDependency": "HIGH"},
            "supplyChain": {"accessibility": "MODERATE", "supplierDependency": "HIGH", "importDependency": True, "deliveryDelayCount": 4, "equipmentAvailability": "SHORTAGE"},
            "legalSocial": {"oppositionLevel": "LOW"},
        },
        "recommendations": [
            "Review delayed project milestones and escalate supply issues",
            "Engage with state transmission utility for grid connection timeline",
            "Procure alternative panel suppliers to mitigate supply risk",
            "Increase monitoring frequency to track module delivery schedule",
            "Negotiate revised delivery timelines with primary contractor",
        ],
    },
    {
        "id": "PRJ-005",
        "name": "Rural Road Connectivity Programme - Assam",
        "ministry": "Ministry of Rural Development",
        "sector": "Transport",
        "state": "Assam",
        "agency": "Pradhan Mantri Gram Sadak Yojana - Assam",
        "original_cost": 3500,
        "current_cost": 3700,
        "expenditure": 3100,
        "physical_progress": 85,
        "planned_progress": 88,
        "start_date": "2022-04-01",
        "expected_completion": "2025-10-31",
        "predicted_completion": "2026-01-31",
        "cost_overrun_probability": 18,
        "delay_probability": 25,
        "implementation_risk": 15,
        "risk_score": 22,
        "risk_level": "LOW",
        "milestones_total": 14,
        "milestones_delayed": 2,
        "lat": 26.50,
        "lng": 90.20,
        "risk_factors": [
            "Physical progress is 3% behind planned progress",
            "Minor cost increase of 5.7% from original estimate",
            "2 of 14 milestones delayed by less than 30 days",
        ],
        "risk_inputs": {
            "weather": {"condition": "CLEAR", "disruption": "LOW", "workingDaysLost": 2},
            "ground": {"condition": "FAVOURABLE"},
            "calamity": {"floodExposure": "LOW"},
            "material": {"availability": "ADEQUATE", "priceIncreasePct": 2},
            "workforce": {"availability": "ADEQUATE", "productivity": "HIGH", "absenteeism": "LOW"},
            "contractor": {"performance": "GOOD", "delayedMilestoneCount": 1},
            "engineering": {"reworkLevel": "NONE", "technicalComplexity": "LOW"},
            "clearance": {"landAcquiredPct": 100, "environmentalClearance": "CLEARED"},
            "administrative": {"turnaround": "FAST", "pendingApprovalCount": 1},
            "supplyChain": {"accessibility": "GOOD", "supplierDependency": "LOW"},
            "legalSocial": {"oppositionLevel": "NONE", "activeDisputeCount": 0},
        },
        "recommendations": [
            "Continue current monitoring schedule",
            "Review remaining milestones for on-time completion",
            "Ensure quality checks before final handover",
        ],
    },
    {
        "id": "PRJ-006",
        "name": "Regional Airport Modernization Project",
        "ministry": "Ministry of Civil Aviation",
        "sector": "Transport",
        "state": "Karnataka",
        "agency": "Airports Authority of India",
        "original_cost": 8200,
        "current_cost": 9400,
        "expenditure": 6500,
        "physical_progress": 58,
        "planned_progress": 70,
        "start_date": "2020-09-01",
        "expected_completion": "2025-12-31",
        "predicted_completion": "2026-09-30",
        "cost_overrun_probability": 55,
        "delay_probability": 65,
        "implementation_risk": 52,
        "risk_score": 58,
        "risk_level": "MEDIUM",
        "milestones_total": 22,
        "milestones_delayed": 8,
        "lat": 12.97,
        "lng": 77.59,
        "risk_factors": [
            "Physical progress is 12% behind planned progress",
            "Cost has increased by 14.6% from original estimate",
            "8 of 22 milestones are delayed",
            "Terminal building design revisions causing delays",
            "ATC equipment procurement facing international supply constraints",
        ],
        "risk_inputs": {
            "weather": {"condition": "MILD"},
            "ground": {"condition": "FAVOURABLE"},
            "calamity": {"earthquakeExposure": "LOW"},
            "material": {"availability": "TIGHT", "priceIncreasePct": 6},
            "workforce": {"availability": "ADEQUATE", "productivity": "NORMAL"},
            "contractor": {"performance": "GOOD", "delayedMilestoneCount": 4},
            "engineering": {"reworkLevel": "MODERATE", "designChangeCount": 8, "designErrorCount": 2, "approvalPending": True},
            "clearance": {"landAcquiredPct": 100, "environmentalClearance": "PENDING"},
            "administrative": {"turnaround": "NORMAL", "pendingApprovalCount": 6, "interDepartmentDependency": "HIGH"},
            "supplyChain": {"supplierDependency": "MODERATE", "importDependency": True, "deliveryDelayCount": 3},
            "legalSocial": {"oppositionLevel": "LOW"},
        },
        "recommendations": [
            "Finalize terminal building design to prevent further revisions",
            "Expedite ATC equipment procurement through alternative vendors",
            "Coordinate with state civil aviation department for clearances",
            "Review remaining milestones and prioritize critical path items",
            "Establish bi-weekly progress review meetings",
        ],
    },
]

SEED_ALERTS = [
    {
        "id": "ALR-001",
        "project_id": "PRJ-003",
        "type": "Schedule Delay Risk",
        "severity": "CRITICAL",
        "detected_date": "2025-09-02",
        "status": "ACTIVE",
        "description": "River Basin Development Project has an estimated 88% probability of schedule delay due to prolonged land acquisition delays and flood damage to completed infrastructure.",
    },
    {
        "id": "ALR-002",
        "project_id": "PRJ-003",
        "type": "Cost Escalation",
        "severity": "CRITICAL",
        "detected_date": "2025-08-18",
        "status": "ACTIVE",
        "description": "River Basin Development Project shows a significant upward cost trend with 21.3% overrun detected. Expenditure utilization at 66.7% indicates further spending delays.",
    },
    {
        "id": "ALR-003",
        "project_id": "PRJ-001",
        "type": "Budget Overrun Alert",
        "severity": "HIGH",
        "detected_date": "2025-10-05",
        "status": "ACTIVE",
        "description": "National Highway Development Project has expended 90.2% of current cost allocation with only 67% physical progress achieved. Land acquisition in 3 stretches remains pending.",
    },
    {
        "id": "ALR-004",
        "project_id": "PRJ-002",
        "type": "Milestone Delay",
        "severity": "HIGH",
        "detected_date": "2025-07-30",
        "status": "ACTIVE",
        "description": "Eastern Dedicated Freight Corridor has 11 of 32 milestones overdue including critical bridge construction sections across river crossings.",
    },
    {
        "id": "ALR-005",
        "project_id": "PRJ-004",
        "type": "Implementation Bottleneck",
        "severity": "MEDIUM",
        "detected_date": "2025-11-12",
        "status": "ACTIVE",
        "description": "Ultra Mega Solar Park Expansion facing module supply chain issues. Transmission line connectivity with state grid delayed by 3 months.",
    },
    {
        "id": "ALR-006",
        "project_id": "PRJ-006",
        "type": "Progress Variance",
        "severity": "MEDIUM",
        "detected_date": "2025-06-22",
        "status": "ACTIVE",
        "description": "Regional Airport Modernization Project shows a 12% gap between planned and actual physical progress. Terminal building design revisions contributing to delays.",
    },
    {
        "id": "ALR-007",
        "project_id": "PRJ-001",
        "type": "Cost Escalation",
        "severity": "MEDIUM",
        "detected_date": "2025-12-01",
        "status": "ACTIVE",
        "description": "National Highway Development Project is projected to exceed original cost estimates by 18.1% based on current expenditure trajectory. Monsoon disruptions recurring.",
    },
    {
        "id": "ALR-008",
        "project_id": "PRJ-003",
        "type": "Implementation Bottleneck",
        "severity": "CRITICAL",
        "detected_date": "2025-07-30",
        "status": "ACTIVE",
        "description": "River Basin Development Project faces critical implementation bottlenecks. 12 of 18 milestones delayed including 5 critical path items.",
    },
    {
        "id": "ALR-009",
        "project_id": "PRJ-006",
        "type": "Schedule Delay Risk",
        "severity": "MEDIUM",
        "detected_date": "2026-02-03",
        "status": "ACTIVE",
        "description": "Regional Airport Modernization Project delay probability has increased to 65% following terminal design revisions and ATC equipment procurement delays.",
    },
    {
        "id": "ALR-010",
        "project_id": "PRJ-005",
        "type": "Progress Variance",
        "severity": "RESOLVED",
        "detected_date": "2025-05-18",
        "status": "RESOLVED",
        "description": "Rural Road Connectivity Programme minor milestone delay resolved. Revised logistics arrangements put in place for remaining construction materials.",
    },
]

SEED_PROJECT_UPDATES = [
    # --- PRJ-001 NH-48: broadly stable, mild recurring schedule pressure ---
    {
        "project_id": "PRJ-001",
        "user_id": "USR-0002",
        "type": "PROGRESS",
        "created_at": "2025-11-10T10:30:00+00:00",
        "content": "Monsoon disruption in the Pune section; monthly progress slipped 2% during the rainy weeks.",
    },
    {
        "project_id": "PRJ-001",
        "user_id": "USR-0002",
        "type": "RISK",
        "created_at": "2025-12-05T09:15:00+00:00",
        "content": "Land acquisition compensation cases for 3 stretches are now before the revenue court.",
    },
    {
        "project_id": "PRJ-001",
        "user_id": "USR-0003",
        "type": "GENERAL",
        "created_at": "2026-01-08T11:45:00+00:00",
        "content": "Meeting with district administration held; a disbursement schedule for compensation has been agreed.",
    },
    {
        "project_id": "PRJ-001",
        "user_id": "USR-0002",
        "type": "PROGRESS",
        "created_at": "2026-02-12T13:20:00+00:00",
        "content": "Sections A and C are on track after the monsoon; 810 of 850 km of concreting completed.",
    },
    {
        "project_id": "PRJ-001",
        "user_id": "USR-0002",
        "type": "GENERAL",
        "created_at": "2026-03-20T08:50:00+00:00",
        "content": "Utility shifting on section B caused a short delay; the contractor deployed extra crew to recover.",
    },
    {
        "project_id": "PRJ-001",
        "user_id": "USR-0003",
        "type": "PROGRESS",
        "created_at": "2026-06-15T10:05:00+00:00",
        "content": "Progress improved this quarter; 5 of 9 delayed milestones recovered and work is broadly on track for the revised completion.",
    },
    {
        "project_id": "PRJ-001",
        "user_id": "USR-0002",
        "type": "GENERAL",
        "created_at": "2026-08-28T12:00:00+00:00",
        "content": "Monthly review: physical progress 67% versus planned 78%; land cases moving steadily, position stable with no new material risks.",
    },
    # --- PRJ-002 Freight Corridor: emerging stakeholder/community risk ---
    {
        "project_id": "PRJ-002",
        "user_id": "USR-0002",
        "type": "PROGRESS",
        "created_at": "2025-10-08T09:40:00+00:00",
        "content": "Bridge piling across the Jalangi river completed ahead of schedule.",
    },
    {
        "project_id": "PRJ-002",
        "user_id": "USR-0002",
        "type": "GENERAL",
        "created_at": "2025-12-15T10:25:00+00:00",
        "content": "Land compensation for 42 affected households in the Hooghly section has been approved.",
    },
    {
        "project_id": "PRJ-002",
        "user_id": "USR-0003",
        "type": "RISK",
        "created_at": "2026-02-10T14:10:00+00:00",
        "content": "Residents in the Murshidabad section have objected to the revised corridor alignment.",
    },
    {
        "project_id": "PRJ-002",
        "user_id": "USR-0002",
        "type": "RISK",
        "created_at": "2026-03-05T11:30:00+00:00",
        "content": "Community protest over tree felling has delayed work near the canal crossing.",
    },
    {
        "project_id": "PRJ-002",
        "user_id": "USR-0003",
        "type": "GENERAL",
        "created_at": "2026-04-18T15:00:00+00:00",
        "content": "Stakeholder meeting held; the objections will be examined by the district committee next month.",
    },
    {
        "project_id": "PRJ-002",
        "user_id": "USR-0002",
        "type": "PROGRESS",
        "created_at": "2026-06-10T09:50:00+00:00",
        "content": "Physical progress 72% versus planned 85%; unresolved stakeholder issues continue to affect two sections.",
    },
    {
        "project_id": "PRJ-002",
        "user_id": "USR-0003",
        "type": "RISK",
        "created_at": "2026-08-30T10:10:00+00:00",
        "content": "Further objections raised by local residents over noise and land values; engaging the district collector this week.",
    },
    # --- PRJ-003 River Basin: cost escalation + funding/resource stress ---
    {
        "project_id": "PRJ-003",
        "user_id": "USR-0002",
        "type": "RISK",
        "created_at": "2025-09-20T08:35:00+00:00",
        "content": "Cement and steel prices rose again this quarter; cost escalation continues across major works packages.",
    },
    {
        "project_id": "PRJ-003",
        "user_id": "USR-0002",
        "type": "GENERAL",
        "created_at": "2025-11-12T12:40:00+00:00",
        "content": "Flood damaged two completed embankment stretches; restoration estimate is still pending.",
    },
    {
        "project_id": "PRJ-003",
        "user_id": "USR-0003",
        "type": "RISK",
        "created_at": "2026-01-25T10:15:00+00:00",
        "content": "Material shortage on site; procurement is delayed and critical aggregate supply remains unreliable.",
    },
    {
        "project_id": "PRJ-003",
        "user_id": "USR-0001",
        "type": "RISK",
        "created_at": "2026-03-15T09:05:00+00:00",
        "content": "Funding release delayed by the finance branch; contractor payments are pending for two months.",
    },
    {
        "project_id": "PRJ-003",
        "user_id": "USR-0003",
        "type": "RISK",
        "created_at": "2026-05-08T14:30:00+00:00",
        "content": "Cash flow stress is delaying critical masonry works; the contractor has flagged further cost overrun.",
    },
    {
        "project_id": "PRJ-003",
        "user_id": "USR-0001",
        "type": "RISK",
        "created_at": "2026-07-01T11:20:00+00:00",
        "content": "Cost overrun now exceeds 21%; seeking supplementary budget sanction from the finance cell.",
    },
    {
        "project_id": "PRJ-003",
        "user_id": "USR-0002",
        "type": "GENERAL",
        "created_at": "2026-08-22T13:45:00+00:00",
        "content": "Workforce shortage persists; both cost and schedule remain under severe pressure this month.",
    },
    # --- PRJ-004 Solar Park: escalation path toward critical ---
    {
        "project_id": "PRJ-004",
        "user_id": "USR-0002",
        "type": "PROGRESS",
        "created_at": "2025-09-18T10:00:00+00:00",
        "content": "Module procurement on track; the first inventory batch has been delivered to site.",
    },
    {
        "project_id": "PRJ-004",
        "user_id": "USR-0003",
        "type": "RISK",
        "created_at": "2025-11-30T09:30:00+00:00",
        "content": "Panel prices have risen 15%; supply chain is under pressure from the global module shortage.",
    },
    {
        "project_id": "PRJ-004",
        "user_id": "USR-0002",
        "type": "RISK",
        "created_at": "2026-01-15T14:50:00+00:00",
        "content": "Import clearance delayed; two module shipments are held at the port.",
    },
    {
        "project_id": "PRJ-004",
        "user_id": "USR-0003",
        "type": "GENERAL",
        "created_at": "2026-03-10T11:10:00+00:00",
        "content": "Transmission line connectivity with the state grid is pending; approval is still awaited.",
    },
    {
        "project_id": "PRJ-004",
        "user_id": "USR-0002",
        "type": "RISK",
        "created_at": "2026-05-05T08:55:00+00:00",
        "content": "Contractor faces module supply issues affecting three blocks; procurement is delayed and work slowed.",
    },
    {
        "project_id": "PRJ-004",
        "user_id": "USR-0003",
        "type": "RISK",
        "created_at": "2026-07-20T15:15:00+00:00",
        "content": "Risk level elevated after repeated supply disruptions; milestone 12 now at risk of delay.",
    },
    {
        "project_id": "PRJ-004",
        "user_id": "USR-0001",
        "type": "GENERAL",
        "created_at": "2026-08-27T12:20:00+00:00",
        "content": "Monthly review: escalation in both cost and delay signals; recommend elevated monitoring status.",
    },
    # --- PRJ-005 Rural Road: improving trend ---
    {
        "project_id": "PRJ-005",
        "user_id": "USR-0002",
        "type": "PROGRESS",
        "created_at": "2026-02-10T09:25:00+00:00",
        "content": "Monsoon damage on a 2 km surface repaired; work resumed on the full stretch.",
    },
    {
        "project_id": "PRJ-005",
        "user_id": "USR-0003",
        "type": "GENERAL",
        "created_at": "2026-04-14T10:40:00+00:00",
        "content": "Bitumen supply issue resolved; an alternative vendor has been arranged.",
    },
    {
        "project_id": "PRJ-005",
        "user_id": "USR-0002",
        "type": "PROGRESS",
        "created_at": "2026-06-05T11:05:00+00:00",
        "content": "Progress ahead of plan; two previously delayed milestones were completed ahead of schedule.",
    },
    {
        "project_id": "PRJ-005",
        "user_id": "USR-0003",
        "type": "GENERAL",
        "created_at": "2026-07-18T13:30:00+00:00",
        "content": "Quality inspections passed; rehabilitation works for the low-lying culverts cleared.",
    },
    {
        "project_id": "PRJ-005",
        "user_id": "USR-0002",
        "type": "PROGRESS",
        "created_at": "2026-08-21T09:10:00+00:00",
        "content": "Project within budget; final pavement works on track and targeted for early handover.",
    },
    # --- PRJ-006 Airport: schedule-delay pressure, design/approval bottlenecks ---
    {
        "project_id": "PRJ-006",
        "user_id": "USR-0002",
        "type": "GENERAL",
        "created_at": "2025-09-30T10:20:00+00:00",
        "content": "Terminal design revision 4 submitted; structural approvals still pending with the design cell.",
    },
    {
        "project_id": "PRJ-006",
        "user_id": "USR-0003",
        "type": "RISK",
        "created_at": "2025-12-10T14:05:00+00:00",
        "content": "ATC equipment procurement delayed by an international supplier.",
    },
    {
        "project_id": "PRJ-006",
        "user_id": "USR-0002",
        "type": "RISK",
        "created_at": "2026-02-08T09:45:00+00:00",
        "content": "Schedule slippage of four weeks reported on the terminal roof works.",
    },
    {
        "project_id": "PRJ-006",
        "user_id": "USR-0003",
        "type": "GENERAL",
        "created_at": "2026-04-15T11:55:00+00:00",
        "content": "Design change order approved; rework now in progress on the concourse area.",
    },
    {
        "project_id": "PRJ-006",
        "user_id": "USR-0002",
        "type": "RISK",
        "created_at": "2026-06-20T10:35:00+00:00",
        "content": "Approval pending for runway lighting; associated civil works are delayed.",
    },
    {
        "project_id": "PRJ-006",
        "user_id": "USR-0003",
        "type": "RISK",
        "created_at": "2026-08-05T09:20:00+00:00",
        "content": "Cumulative delay now around nine months; runway and terminal both on the critical path and slipping.",
    },
    {
        "project_id": "PRJ-006",
        "user_id": "USR-0002",
        "type": "GENERAL",
        "created_at": "2026-08-26T12:45:00+00:00",
        "content": "Next milestone at risk of delay; a recovery plan has been submitted for review.",
    },
]
