import json

SEED_PROJECTS = [
    {
        "id": "PRJ-001",
        "name": "National Highway Development Project (NH-48 Expansion)",
        "ministry": "Ministry of Road Transport and Highways",
        "sector": "Transport",
        "state": "Maharashtra",
        "agency": "National Highways Authority of India",
        "original_cost": 24500,
        "current_cost": 28930,
        "expenditure": 22100,
        "physical_progress": 67,
        "planned_progress": 78,
        "start_date": "2021-04-15",
        "expected_completion": "2025-12-31",
        "predicted_completion": "2027-03-15",
        "cost_overrun_probability": 72,
        "delay_probability": 79,
        "implementation_risk": 65,
        "risk_score": 74,
        "risk_level": "HIGH",
        "milestones_total": 24,
        "milestones_delayed": 9,
        "lat": 18.52,
        "lng": 73.85,
        "risk_factors": [
            "Physical progress is 11% behind planned progress",
            "Cost has increased by 18.1% from original estimate",
            "9 of 24 milestones are delayed",
            "Land acquisition pending in 3 critical stretches",
            "Monsoon season causing recurring construction pauses",
        ],
        "recommendations": [
            "Review delayed project milestones and prepare recovery plan",
            "Escalate land acquisition issues to state revenue department",
            "Increase monitoring frequency to bi-weekly status reviews",
            "Deploy additional resources for critical path activities",
            "Engage with district collectors for faster approvals",
        ],
    },
    {
        "id": "PRJ-002",
        "name": "Eastern Dedicated Freight Corridor",
        "ministry": "Ministry of Railways",
        "sector": "Transport",
        "state": "West Bengal",
        "agency": "Dedicated Freight Corridor Corporation of India",
        "original_cost": 48500,
        "current_cost": 53200,
        "expenditure": 41800,
        "physical_progress": 72,
        "planned_progress": 85,
        "start_date": "2019-07-01",
        "expected_completion": "2026-06-30",
        "predicted_completion": "2027-10-30",
        "cost_overrun_probability": 68,
        "delay_probability": 82,
        "implementation_risk": 61,
        "risk_score": 71,
        "risk_level": "HIGH",
        "milestones_total": 32,
        "milestones_delayed": 11,
        "lat": 22.82,
        "lng": 88.18,
        "risk_factors": [
            "Physical progress is 13% behind planned progress",
            "Cost overrun of 9.7% from original estimate",
            "11 of 32 milestones are overdue",
            "Bridge construction across multiple river crossings delayed",
            "Utility relocation conflicts in several sections",
        ],
        "recommendations": [
            "Conduct contractor performance assessment for delayed sections",
            "Reassess project timeline with revised critical path analysis",
            "Coordinate with state utilities for expedited relocation",
            "Deploy additional engineering teams for bridge construction",
            "Establish weekly progress review meetings with all stakeholders",
        ],
    },
    {
        "id": "PRJ-003",
        "name": "River Basin Development Project",
        "ministry": "Ministry of Jal Shakti",
        "sector": "Water",
        "state": "Bihar",
        "agency": "Central Water Commission",
        "original_cost": 4800,
        "current_cost": 5822,
        "expenditure": 3200,
        "physical_progress": 48,
        "planned_progress": 62,
        "start_date": "2020-01-15",
        "expected_completion": "2025-08-31",
        "predicted_completion": "2027-12-31",
        "cost_overrun_probability": 76,
        "delay_probability": 88,
        "implementation_risk": 68,
        "risk_score": 91,
        "risk_level": "CRITICAL",
        "milestones_total": 18,
        "milestones_delayed": 12,
        "lat": 25.43,
        "lng": 85.62,
        "risk_factors": [
            "Physical progress is 14% behind planned progress",
            "Cost has increased by 21.3% from original estimate",
            "12 of 18 milestones are delayed including 5 critical ones",
            "Flood season has damaged completed infrastructure",
            "Expenditure utilization at 66.7% indicates spending delays",
        ],
        "recommendations": [
            "Conduct urgent review of all delayed milestones",
            "Prepare flood damage assessment and restoration plan",
            "Engage with state irrigation department for coordination",
            "Request additional budget allocation for flood mitigation",
            "Deploy rapid assessment team for on-site evaluation",
        ],
    },
    {
        "id": "PRJ-004",
        "name": "Ultra Mega Solar Park Expansion",
        "ministry": "Ministry of New and Renewable Energy",
        "sector": "Energy",
        "state": "Rajasthan",
        "agency": "Solar Energy Corporation of India",
        "original_cost": 12800,
        "current_cost": 14520,
        "expenditure": 11200,
        "physical_progress": 73,
        "planned_progress": 82,
        "start_date": "2021-06-01",
        "expected_completion": "2025-10-31",
        "predicted_completion": "2026-08-15",
        "cost_overrun_probability": 58,
        "delay_probability": 69,
        "implementation_risk": 55,
        "risk_score": 63,
        "risk_level": "HIGH",
        "milestones_total": 20,
        "milestones_delayed": 7,
        "lat": 27.53,
        "lng": 71.92,
        "risk_factors": [
            "Physical progress is 9% behind planned progress",
            "Cost overrun of 13.4% due to panel price escalation",
            "Transmission line connectivity delays with state grid",
            "Sandstorm disruptions during summer months",
            "Contractor facing module supply chain issues",
        ],
        "recommendations": [
            "Review delayed project milestones and escalate supply issues",
            "Engage with state transmission utility for grid connection timeline",
            "Procure alternative panel suppliers to mitigate supply risk",
            "Increase monitoring frequency to track module delivery schedule",
            "Negotiate revised delivery timelines with primary contractor",
        ],
    },
    {
        "id": "PRJ-005",
        "name": "Rural Road Connectivity Programme - Assam",
        "ministry": "Ministry of Rural Development",
        "sector": "Transport",
        "state": "Assam",
        "agency": "Pradhan Mantri Gram Sadak Yojana - Assam",
        "original_cost": 3500,
        "current_cost": 3700,
        "expenditure": 3100,
        "physical_progress": 85,
        "planned_progress": 88,
        "start_date": "2022-04-01",
        "expected_completion": "2025-10-31",
        "predicted_completion": "2026-01-31",
        "cost_overrun_probability": 18,
        "delay_probability": 25,
        "implementation_risk": 15,
        "risk_score": 22,
        "risk_level": "LOW",
        "milestones_total": 14,
        "milestones_delayed": 2,
        "lat": 26.50,
        "lng": 90.20,
        "risk_factors": [
            "Physical progress is 3% behind planned progress",
            "Minor cost increase of 5.7% from original estimate",
            "2 of 14 milestones delayed by less than 30 days",
        ],
        "recommendations": [
            "Continue current monitoring schedule",
            "Review remaining milestones for on-time completion",
            "Ensure quality checks before final handover",
        ],
    },
    {
        "id": "PRJ-006",
        "name": "Regional Airport Modernization Project",
        "ministry": "Ministry of Civil Aviation",
        "sector": "Transport",
        "state": "Karnataka",
        "agency": "Airports Authority of India",
        "original_cost": 8200,
        "current_cost": 9400,
        "expenditure": 6500,
        "physical_progress": 58,
        "planned_progress": 70,
        "start_date": "2020-09-01",
        "expected_completion": "2025-12-31",
        "predicted_completion": "2026-09-30",
        "cost_overrun_probability": 55,
        "delay_probability": 65,
        "implementation_risk": 52,
        "risk_score": 58,
        "risk_level": "MEDIUM",
        "milestones_total": 22,
        "milestones_delayed": 8,
        "lat": 12.97,
        "lng": 77.59,
        "risk_factors": [
            "Physical progress is 12% behind planned progress",
            "Cost has increased by 14.6% from original estimate",
            "8 of 22 milestones are delayed",
            "Terminal building design revisions causing delays",
            "ATC equipment procurement facing international supply constraints",
        ],
        "recommendations": [
            "Finalize terminal building design to prevent further revisions",
            "Expedite ATC equipment procurement through alternative vendors",
            "Coordinate with state civil aviation department for clearances",
            "Review remaining milestones and prioritize critical path items",
            "Establish bi-weekly progress review meetings",
        ],
    },
]

SEED_ALERTS = [
    {
        "id": "ALR-001",
        "project_id": "PRJ-003",
        "type": "Schedule Delay Risk",
        "severity": "CRITICAL",
        "detected_date": "2025-09-02",
        "status": "ACTIVE",
        "description": "River Basin Development Project has an estimated 88% probability of schedule delay due to prolonged land acquisition delays and flood damage to completed infrastructure.",
    },
    {
        "id": "ALR-002",
        "project_id": "PRJ-003",
        "type": "Cost Escalation",
        "severity": "CRITICAL",
        "detected_date": "2025-08-18",
        "status": "ACTIVE",
        "description": "River Basin Development Project shows a significant upward cost trend with 21.3% overrun detected. Expenditure utilization at 66.7% indicates further spending delays.",
    },
    {
        "id": "ALR-003",
        "project_id": "PRJ-001",
        "type": "Budget Overrun Alert",
        "severity": "HIGH",
        "detected_date": "2025-10-05",
        "status": "ACTIVE",
        "description": "National Highway Development Project has expended 90.2% of current cost allocation with only 67% physical progress achieved. Land acquisition in 3 stretches remains pending.",
    },
    {
        "id": "ALR-004",
        "project_id": "PRJ-002",
        "type": "Milestone Delay",
        "severity": "HIGH",
        "detected_date": "2025-07-30",
        "status": "ACTIVE",
        "description": "Eastern Dedicated Freight Corridor has 11 of 32 milestones overdue including critical bridge construction sections across river crossings.",
    },
    {
        "id": "ALR-005",
        "project_id": "PRJ-004",
        "type": "Implementation Bottleneck",
        "severity": "MEDIUM",
        "detected_date": "2025-11-12",
        "status": "ACTIVE",
        "description": "Ultra Mega Solar Park Expansion facing module supply chain issues. Transmission line connectivity with state grid delayed by 3 months.",
    },
    {
        "id": "ALR-006",
        "project_id": "PRJ-006",
        "type": "Progress Variance",
        "severity": "MEDIUM",
        "detected_date": "2025-06-22",
        "status": "ACTIVE",
        "description": "Regional Airport Modernization Project shows a 12% gap between planned and actual physical progress. Terminal building design revisions contributing to delays.",
    },
    {
        "id": "ALR-007",
        "project_id": "PRJ-001",
        "type": "Cost Escalation",
        "severity": "MEDIUM",
        "detected_date": "2025-12-01",
        "status": "ACTIVE",
        "description": "National Highway Development Project is projected to exceed original cost estimates by 18.1% based on current expenditure trajectory. Monsoon disruptions recurring.",
    },
    {
        "id": "ALR-008",
        "project_id": "PRJ-003",
        "type": "Implementation Bottleneck",
        "severity": "CRITICAL",
        "detected_date": "2025-07-30",
        "status": "ACTIVE",
        "description": "River Basin Development Project faces critical implementation bottlenecks. 12 of 18 milestones delayed including 5 critical path items.",
    },
    {
        "id": "ALR-009",
        "project_id": "PRJ-006",
        "type": "Schedule Delay Risk",
        "severity": "MEDIUM",
        "detected_date": "2026-02-03",
        "status": "ACTIVE",
        "description": "Regional Airport Modernization Project delay probability has increased to 65% following terminal design revisions and ATC equipment procurement delays.",
    },
    {
        "id": "ALR-010",
        "project_id": "PRJ-005",
        "type": "Progress Variance",
        "severity": "RESOLVED",
        "detected_date": "2025-05-18",
        "status": "RESOLVED",
        "description": "Rural Road Connectivity Programme minor milestone delay resolved. Revised logistics arrangements put in place for remaining construction materials.",
    },
]
